#Developed by _ItsAndrew_
#This file is for configuring the discord bot.

#Configure the main bot principles
guild-id: "" #This is the ID your discord server has. To get it, turn on 'Developer Mode', right click on your server and click on 'Copy ID'
bot-token: "" #This is the token of a bot. To run the bot, you will need to create an app yourself in the Discord Developer Portal.
#After you create an app, go to 'bot' section, copy the token and paste it here. To invite the bot to your server, go to 'OAuth2' section and generate a URL.

#Messages. They support MARKDOWN! 'Set ephemeral' makes the message appear only to that user
invalid-expired-code-message: "**Invalid** or **expired** verification code!"
iecm-set-ephemeral: true
player-verified-message: "âœ… You are now verified! Run **/verify** again in Minecraft!"
pvm-set-ephemeral: true

#Set the minutes for the interactions
interaction-minutes: 2 #If a user is having an interaction and he doesn't do anything for some minutes, it removes the user from it.
