#Developed by _ItsAndrew_
#This file is for configuring the discord bot.

#Configure the main bot principles
guild-id:  #This is the ID your discord server has. To get it, turn on 'Developer Mode', right click on your server and click on 'Copy ID'
bot-token:  #This is the token of a bot. To run the bot, you will need to create an app yourself in the Discord Developer Portal.
#After you create an app, go to 'bot' section, copy the token and paste it here. To invite the bot to your server, go to 'OAuth2' section and generate a URL.

#Enter the ID of which roles need to be deleted from the users when running the bot for the first time.
#This is to help a task which automatically gives users from your server the 'Unverified' role and removing the other roles.
roles-to-be-deleted:
  -

#Messages. They support MARKDOWN! 'Set ephemeral' makes the message appear only to that user
invalid-expired-code-message: "**Invalid** or **expired** verification code!"
iecm-set-ephemeral: true
player-verified-message: "‚úÖ You are now verified! Have fun on our server!"
pvm-set-ephemeral: true

#Set the minutes for the interactions
interaction-minutes: 2 #If a user is having an interaction and he doesn't do anything for some minutes, it removes the user from it.

#Set the Minimum and Maximum length for the punishment reason modal (In characters!)
minimum-length-reason: 5
maximum-length-reason: 2000

#Set the Minimum and Maximum length for the duration modal (In Characters!)
minimum-length-duration: 2
maximum-length-duration: 15

#Configure the punishment appeal. Use '\n' for line breaks
minimum-length-appeal: 75 #In characters!
maximum-length-appeal: 4000 #In characters! MAX IS 4000!!!
placeholder-appeal: "In detail, explain anything related to the punishment you've received. \nMINIMUM 100 WORDS!"
appeal-channel-id:  #The channel where the appeals will show up

#Configure a task for command logging. You will need to set up a channel for this!
command-logging:
  toggle: true #Whether you want to use this feature or not.
  channel-id:
  embed-color:
    RED: 0
    GREEN: 255
    BLUE: 255
  embed-title: "COMMAND RAN BY **%player_name%**" #Use %player_name% to display the player's name
  #Use '%command%' to display the command with it's arguments
  embed-description: "
  **Command Executed**: %command%
  "
  not-tracking-these-commands: #Here put the names of the commands you don't want to log
    - ""

#Configure the member join event. You will need to create 2 roles and a verify channel!
verification:
  verified-role-id:  #This role will be a 'Member' type role. It will be used to let the user see the other channels
  unverified-role-id:  #This one is used to only show the 'verify' channel
  verify-channel-id:  #The ID of the verification channel. IT MUST BE EMPTY, WITH NO TEXT HISTORY!!!

  #Configure the verify channel embed. It is helpful for players to know what to do when they join the server.
  #For description, you can use '\n' for line breaks.
  #Placeholders: %server_name% -> Displays the discord server's name
  verify-channel-embed-description: "**Welcome to %server_name%!**\n\nTo start your adventure: \n1.) Head over to our **Minecraft Server**\n2.) Run */verify* to get a **code**\n3.) Come back here and run */verify <code>*\n4.) Have fun on our server!"
  verify-channel-embed-title: "VERIFY YOUR ACCOUNT!"
  verify-channel-embed-color: #This will work in R-red G-green B-blue format!
    RED: 138
    GREEN: 43
    BLUE: 226

#Configure the Timeout Role for the punishments. You will also have to create one for this.
timeout-role-id:

#Configure the Ban Channel and Banned Role ID. This is needed for users that are banned.
ban-role-id:
banned-users-channel:
  id:

  #Configure the embed that will be sent to the channel. For description, use '\n' for line breaks.
  embed-title: "HOW TO APPEAL"
  embed-color:
    RED: 255
    GREEN: 0
    BLUE: 0
  embed-description: "If you see this. You might have been banned on **discord** or **globally**.
  \nIf you think you didn't deserve the ban, here is how you can appeal your punishment.
  \n\n1Ô∏è‚É£You should have received a message in the DM with information of the ban. Go in the bot DM.
  \n\n2Ô∏è‚É£Run **/appeal** with the ID of your ban.
  \n\n3Ô∏è‚É£Complete the form that you were prompted. *Be careful! You only have **1** appeal.*
  \n\n4Ô∏è‚É£Wait for a response. We wish you luck üôè!
  \n\n**P.S.**: If you didn't get a DM, click the button below to get your ban ID. Then, run **/appeal <id>** here!
  "

#Configure what role the user must have to use the specific command. You will enter the ID of the roles!!
pshistory-cmd-roles: #This only works for '/pshistory <ign>'!! Everyone will be able to run only '/pshistory'
  -

punish-cmd-roles:
  -

psremove-cmd-roles:
  -

RefreshVerification-cmd-roles:
  -

#Configure the logs system. This is for staff to see each punishment that has been applied.
use-logs: true #If you want to use logs or not.
logs:
  use-only-one-channel: false #This is if you want to use only one channel for ALL logs. (false -> no / true -> yes)
  channel-id:  #The ID of the channel. Ignore this if you typed 'false' in 'use-only-one-channel'!!
  multiple-channel-id:
    warnings-channel-id:  #The ID for the warnings channel. This channel will only show warnings!
    kicks-channel-id:  #The ID for the kicks channel. This channel will only show kicks!
    mutes-channel-id:  #The ID for the mute channel. This channel will only show mutes!
    bans-channel-id:  #The ID for the ban channel. This channel will only show mutes!

#Punishments Messages in user's DM. These trigger when you apply a punishment. They are also vital for appealing!
user-punishments-messages:
  #This is the message when a user gets kicked from your server. Use '\n' for line breaks. It supports MARKDOWN!!
  #Placeholders: %user% -> Displays the user's name.
  #              %server_name% -> Displays the discord server's name.
  #              %scope% -> Displays the scope of the punishment
  #              %reason% -> Displays the reason of the punishment
  kick-message: "Dear **%user%**,\n\nYou *have been kicked* from **%server_name%**.\n**Scope**: %scope%\n**Reason**: %reason%"

  #This is the message when a user is banned from the server. Use '\n' for line breaks. It supports MARKDOWN!!
  #Placeholders: %user% -> Displays the user's name.
  #              %server_name% -> Displays the discord server's name.
  #              %scope% -> Displays the scope of the punishment.
  #              %reason% -> Displays the reason of the punishment.
  permanent-ban-message: "Dear **%user%**, \n\nYou *have been **permanently** banned* from **%server_name%**. \n**Scope**: %scope%\n**Reason**: %reason%"

  #The message when a user gets a permanent ban warning on the server. Use '\n' for line breaks. It supports MARKDOWN!!
  #Placeholders: %user% -> Displays the target user's name
  #              %server_name% -> Displays the discord server's name
  #              %reason% -> The reason of the warning
  #              %scope% -> The scope of the warning
  permanent-ban-warn-message: "Dear **%user%**, \n\nYou *got* a **permanent ban warning** on *%server_name%.\n**Scope**: %scope%\n**Reason: %reason%"

  #The message when a user gets a temporary ban on the server. Use '\n' for line breaks. It supports MARKDOWN!!
  #Placeholders: %user% -> Displays the target user's name
  #              %server_name% -> Displays the discord server's name
  #              %reason% -> Displays the reason of the ban
  #              %scope% -> Displays the scope of the ban
  #              %time_left% -> Displays the duration of the ban
  #              %expiration_time% -> Displays the time when the ban will expire
  temporary-ban-message: "Dear **%user%**, \n\nYou *have been **temporarily** banned* for **%time_left%** from **%server_name%**.\n**Scope**: %scope%\n\n**Reason**: %reason%\n**Expires At**: %expiration_time%"

  #The message when a user gets a temporary ban warning on the server. Use '\n' for line breaks. It supports MARKDOWN!!
  #Placeholders: %user% -> Displays the target user's name
  #              %server_name% -> Displays the discord server's name
  #              %scope% -> Displays the scope of the warning
  #              %reason% -> Displays the reason of the warning
  temporary-ban-warn-message: "Dear **%user%**, \n\nYou *got* a **temporary ban warning** on *%server_name%*.\n**Scope**: %scope%\n**Reason**: %reason%"

  #The message when a user gets a permanent timeout on the server. Use '\n' for line breaks. It supports MARKDOWN!!
  #Placeholders: %user% -> Displays the user's name
  #              %server_name% -> Displays the discord server's name
  #              %scope% -> Displays the scope of the timeout
  #              %reason% -> Displays the reason of the timeout
  permanent-timeout-message: "Dear **%user%**, \n\nYou *got* a **permanent timeout** on *%server_name%*. \n**Scope**: %scope%\n**Reason**: %reason%"

  #The message when a target user gets a permanent timeout warning on the server. Use '\n' for line breaks. It supports MARKDOWN!!
  #Placeholders: %user% -> Displays the target user's name
  #              %server_name% -> Displays the discord server's name
  #              %reason% -> Displays the reason of the warning
  #              %scope% -> Displays the scope of the warning
  permanent-timeout-warn-message: "Dear **%user%**, \n\nYou *got* a **permanent timeout warning** on *%server_name%*. \n**Scope**: %scope%\n**Reason**: %reason%"

  #The message when a target user gets a temporary timeout on the server. Use '\n' for line breaks. It supports MARKDOWN!!
  #Placeholders: %user% -> Displays the target user's name
  #              %server_name% -> Displays the discord server's name
  #              %time_left% -> Displays the duration of the timeout
  #              %expiration_time% -> Displays the date when the timeout will expire
  #              %reason% -> Displays the reason of the timeout
  #              %scope% ->Displays the scope of the timeout
  temporary-timeout-message: "Dear **%user%**, \n\nYou *got* a **temporary timeout** for *%time_left%* on *%server_name%*. \n**Scope**: %scope%\n**Reason**: %reason%\n**Expires At**: %expiration_time%"

  #The message when a target user gets a temporary timeout warning on the server. Use '\n' for line breaks. It supports MARKDOWN!!
  #Placeholders: %user% -> Displays the target user's name
  #              %server_name% -> Displays the discord server's name
  #              %reason% -> Displays the reason of the punishment
  #              %scope% -> Displays the scope of the punishment
  temporary-timeout-warn-message: "Dear **%user%**, \n\nYou *got* a **temporary timeout warning** on *%server_name%*. \n**Scope**: %scope%\n**Reason**: %reason%"