#Developed by _ItsAndrew_
#This file is for configuring the discord bot.

#Configure the main bot principles
guild-id: "" #This is the ID your discord server has. To get it, turn on 'Developer Mode', right click on your server and click on 'Copy ID'
bot-token: "" #This is the token of a bot. To run the bot, you will need to create an app yourself in the Discord Developer Portal.
#After you create an app, go to 'bot' section, copy the token and paste it here. To invite the bot to your server, go to 'OAuth2' section and generate a URL.

#Messages. They support MARKDOWN! 'Set ephemeral' makes the message appear only to that user
invalid-expired-code-message: "**Invalid** or **expired** verification code!"
iecm-set-ephemeral: true
player-verified-message: "âœ… You are now verified! Run **/verify** again in Minecraft!"
pvm-set-ephemeral: true

#Set the minutes for the interactions
interaction-minutes: 2 #If a user is having an interaction and he doesn't do anything for some minutes, it removes the user from it.

#Set the Minimum and Maximum length for the reason modal (In characters!)
minimum-length-reason: 10
maximum-length-reason: 2000

#Set the Minimum and Maximum length for the duration modal (In Characters!)
minimum-length-duration: 2
maximum-length-duration: 15

#Punishments Messages in user's DM. These trigger when you apply a punishment.
user-punishments-messages:

  #This is the message when a user gets kicked from your server. Use '\n' for line breaks. It supports MARKDOWN!!
  #Placeholders: %user% -> Displays the user's name.
  #              %server_name% -> Displays the discord server's name.
  #              %scope% -> Displays the scope of the punishment
  #              %reason% -> Displays the reason of the punishment
  kick-message: "Dear **\\%user%**,\n\nYou *have been kicked* from **%server_name%**. See more info below:\n**Reason**: %reason%\n**Scope**: %scope%"