#Developed by _ItsAndrew_
#This file is for configuring the main settings of DiscordUtils.

chat-prefix: "&9&lDU &8>>" #The chat prefix shown to players.

#Broadcast custom message configuration
autobroadcast:
  toggle: true
  interval: 600 #In seconds. For example here the interval is 10 minutes. You will need to RESTART THE SERVER when changing this!
  message-lines: #Use '&' for styles.
    - "&c-----------------------------------------------------"
    - ""
    - "                    &9&lJOIN OUR DISCORD TODAY!"
    - ""
    - "    &7If you didn't know, our server has a &ldiscord server&7!"
    - "                    &7Do &e&l/discord &7for more info."
    - ""
    - "&c-----------------------------------------------------"

#Configure the discord block. Used for players to click it and get the link.
#TIP: For the custom head, go to https://minecraft-heads.com/ , search for a head and copy-paste the VALUE
toggle-discord-block: true #Whether you want this block or not.

toggle-discord-block-particles: true #Whether you want particles or not
discord-block-particle: PORTAL #TIP: Go to https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Particle.html to see each particle's name
particle-count: 40 #The number of particles spawned each time
offsetX: 0.4 #The maximum random offset on the X axis
offsetY: 0.5 #The maximum random offset on the Y axis
offsetZ: 0.4 #The maximum random offset on the Z axis
extra: 0 #Extra data for particle (usually speed)
#TIP: Try to play with these offsets :)

block-world: . #TIP: Look in your server's folder for the world name (ex: world, world_nether, world_the_end etc.)
block-x: .
block-y: .
block-z: .
facing: . #Values: NORTH, WEST, SOUTH, WEST, NORTH-EAST, NORTH-WEST, SOUTH-EAST, SOUTH-WEST
custom-head: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzg3M2MxMmJmZmI1MjUxYTBiODhkNWFlNzVjNzI0N2NiMzlhNzVmZjFhODFjYmU0YzhhMzliMzExZGRlZGEifX19"

#Configure the task of giving players the link.
discord-link: "" #Enter your discord's server invite link
link-appearance-choice: "book" #Whether you want a chat message or a book for displaying the link to the players
hover-text: "Click to enter our server!"

discord-link-word: "here" #The word which has the click and hover event

message-lines: #Use the discord-link-word in your message! The discord-link-word is 'here', so I use 'here' in the message.
  - "&c&lClick &9&lhere &c&lto join our discord server!"

#TIP: You may include as many details as you can if using the book!
book-pages: #Use the discord-link-word in your page! The discord-link-word is 'here', so I use 'here' in the page.
  - "&4&lOUR DISCORD\n\n&c&lClick &9&lhere &c&lto join our discord server!"

#Configure a 'fetching-data' mini task. This task runs after the player clicks on the discord-item in the GUI.
#P.S: It is only for 'professional appearance' :)
fetching-data:
  toggle: true #If you want this feature or not
  chat-message: "&8Fetching data..."
  duration: 3 #In seconds

#Configure the Discord GUI shown to players
discord-gui:
  rows: 6 #The number MUST be between 1 and 6. (1 row has 9 SLOTS).
  title: "Get the discord link!" #Use '&' for styles.

  #Configure the exit item
  exit-item:
    toggle: true #Whether you want this item in the GUI or not
    slot: 40
    display-name: "&cEXIT"
    lore: #Leave blank for no lore
      -
    material: red_concrete

  #Configure the decorations.
  decorations:
    toggle: true #Toggle the decorations
    material: black_stained_glass_pane
    display-name: " "

  #Configure an info item. This item is for displaying additional information
  info-item:
    toggle: true
    slot: 4 #The slot in the GUI
    material: oak_sign #Material of the item
    display-name: "&eGet the &ldiscord server &elink" #Enter the display name of the item\
    lore: #Leave blank for no lore. Used for more additional information
      -

  discord-item: #This is the item gives players the discord link
    #To get a custom head, navigate to https://minecraft-heads.com, search for a head, scroll down and paste the VALUE
    use-custom-head: true
    custom-head: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTNiMTgzYjE0OGI5YjRlMmIxNTgzMzRhZmYzYjViYjZjMmMyZGJiYzRkNjdmNzZhN2JlODU2Njg3YTJiNjIzIn19fQ=="

    #This uses a normal minecraft item
    use-normal-material: false
    material: blue_concrete

    slot: 22
    display-name: "&9Click to get the &linvite link&9!" #Use '&' for styles
    lore: #Leave blank for no lore
      -

#Configure all the messages for DiscordUtils.
error-gui-message: "&cThere was error opening the GUI. Contact the server administrators about this."
command-no-permission-message: "&cYou don't have permission to run this command."
block-no-permission-message: "&cYou don't have permission to get the link."
error-task-message: "&cThere was an error giving the discord link. Contact the server administrators about this."

#Configure all the SOUNDS for DiscordUtils. The default value for volume and sound is 1!
#TIP: do /playsound ... in Minecraft to HEAR the sound and see the sound's NAME.
exit-item-sound: "ui.button.click"
eis-volume: 1
eis-pitch: 1

boardcast-message-sound: "block.note_block.pling"
bms-volume: 1
bms-pitch: 1

get-discord-link-sound: "entity.player.levelup"
gdls-volume: 1
gdls-pitch: 1.4

gui-error-sound: "entity.enderman.teleport"
ges-volume: 1
ges-pitch: 1

task-error-sound: "entity.enderman.teleport"
tes-volume: 1
tes-pitch: 1

player-no-permission-sound: "entity.enderman.teleport" #This sound comes up when the player clicks the discord-block and doesn't have 'discordutils.use' permission
pnps-volume: 1
pnps-pitch: 1

open-discord-gui-sound: "entity.experience_orb.pickup"
odgs-volume: 1
odgs-pitch: 1

#Configure the help book. Use '\n' to go on a new line in a page
help-message-book-pages:
  - " &9&l  DISCORD UTILS        HELP MANUAL\n\n&41. &l/dcutils setdclink <link>\n  &4->set the link of your discord server.\n\n&42. &l/dcutils setdcchoice\n  &4->set the choice of the link's appearance to the player."
  - "&43. &l/dcutils reload\n  &4->reload the config file. Use when manually changing something in it.\n\n&44. &l/dcutils help\n  &4->brings up the help manual.\n\n&45. &l/discord\n  &4->Opens the GUI. Main command for players."