#Developed by _ItsAndrew_
#This file is for configuring the main settings of DiscordUtils.

chat-prefix: "&9&lDU &8>>" #The chat prefix displayed in chat.

#Configure the database system. As you can see, by default the plugin is configured for SQLite.
database-system:
  #This is the type of the database. If you run a network with multiple servers, use 'mysql'! If you run only 1 server, use 'sqlite'!
  type: sqlite
  file-name: "database.db" #This is ONLY for SQLite, and it is ONLY a name for the file

  #These are the settings for the MySQL database. If you don't use MySQL, you can ignore this.
  host:
  port:
  database:
  username:
  password:

#Broadcast custom message configuration
autobroadcast:
  toggle: true
  interval: 600 #In seconds. For example here the interval is 10 minutes. You will need to RESTART THE SERVER when changing this!
  message-lines: #Use '&' for styles.
    - "&c-----------------------------------------------------"
    - ""
    - "                    &9&lJOIN OUR DISCORD TODAY!"
    - ""
    - "    &7If you didn't know, our server has a &ldiscord server&7!"
    - "                    &7Do &e&l/discord &7for more info."
    - ""
    - "&c-----------------------------------------------------"

#Configure the discord block. Used for players to click it and get the link.
#TIP: For the custom head, go to https://minecraft-heads.com/ , search for a head and copy-paste the VALUE
toggle-discord-block: true #Whether you want this block or not.

toggle-discord-block-particles: true #Whether you want particles or not
discord-block-particle: PORTAL #TIP: Go to https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Particle.html to see each particle's name
particle-count: 40 #The number of particles spawned each time
offsetX: 0.4 #The maximum random offset on the X axis
offsetY: 0.5 #The maximum random offset on the Y axis
offsetZ: 0.4 #The maximum random offset on the Z axis
extra: 0 #Extra data for particle (usually speed)
#TIP: Try to play with these values and experiment :)

block-world: . #TIP: Look in your server's folder for the world name (ex: world, world_nether, world_the_end etc.)
block-x: .
block-y: .
block-z: .
facing: . #Values: NORTH, WEST, SOUTH, WEST, NORTH-EAST, NORTH-WEST, SOUTH-EAST, SOUTH-WEST
custom-head: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzg3M2MxMmJmZmI1MjUxYTBiODhkNWFlNzVjNzI0N2NiMzlhNzVmZjFhODFjYmU0YzhhMzliMzExZGRlZGEifX19"

#Configure the task of giving players the link.
discord-link: "" #Enter your discord's server invite link
link-appearance-choice: "book" #Whether you want a chat message or a book for displaying the link to the players. Values: 'book' / 'chat-message'
hover-text: "Click to enter our server!"
discord-link-word: "here" #The word which has the click and hover event
message-lines: #Use the discord-link-word in your message! The discord-link-word is 'here', so I use 'here' in the message.
  - "&c&lClick &9&lhere &c&lto join our discord server!"

#TIP: You may include as many details as you can if using the book!
book-pages: #Use the discord-link-word in your page! The discord-link-word is 'here', so I use 'here' in the page.
  - "&4&lOUR DISCORD\n\n&c&lClick &9&lhere &c&lto join our discord server!"

#Configure a 'fetching-data' mini task. This task runs after the player clicks on the discord-item in the GUI.
#P.S: It is only for 'professional appearance' :)
fetching-data:
  toggle: true #If you want this feature or not
  duration: 3 #In seconds

#Configure the Discord GUI shown to players
discord-gui:
  rows: 6 #The number MUST be between 1 and 6. (1 row has 9 SLOTS).
  title: "Get the discord link!" #Use '&' for styles.

  #Configure the exit item
  exit-item:
    toggle: true #Whether you want this item in the GUI or not
    slot: 40
    display-name: "&cEXIT"
    lore: #Leave blank for no lore
      -
    material: red_concrete

  #Configure the decorations.
  decorations:
    toggle: true #Toggle the decorations
    material: black_stained_glass_pane
    display-name: " "

  #Configure an info item. This item is for displaying additional information
  info-item:
    toggle: true
    slot: 4 #The slot in the GUI
    material: oak_sign #Material of the item
    display-name: "&eGet the &ldiscord server &elink" #Enter the display name of the item\
    lore: #Leave blank for no lore. Used for more additional information
      -

  discord-item: #This is the item gives players the discord link
    #To get a custom head, navigate to https://minecraft-heads.com, search for a head, scroll down and paste the VALUE
    use-custom-head: true
    custom-head: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTNiMTgzYjE0OGI5YjRlMmIxNTgzMzRhZmYzYjViYjZjMmMyZGJiYzRkNjdmNzZhN2JlODU2Njg3YTJiNjIzIn19fQ=="

    #This uses a normal minecraft item
    use-normal-material: false
    material: blue_concrete

    slot: 22
    display-name: "&9Click to get the &linvite link&9!" #Use '&' for styles
    lore: #Leave blank for no lore
      -


#Configure the verification codes task. For messages use '&' for styles.
verification-code-length: 6 #How many digits the verification code will have
verification-code-expire-time: 300 #In seconds!!!
player-already-verifying-message: "&cPlease finish this verification before starting a new one!"
player-is-already-verified-message: "&cYou are already verified!"
error-giving-rewards-message: "&cThere was a problem giving you the rewards. Contact the server administrators about this."
code-expired-message: "&cVerification code expired. Please run &l/verify &cagain."
# %code% -> display the code ; %expire_at% -> display the duration of the code (in minutes)
use-verification-code-message: #You can have more lines
  - "&aYour code is &e&l%code%&a! Do &e&l/verify <code> &ain our discord server to complete the verification."
  - "&cThe code will expire in &l%expire_at% minutes&c!"

player-verified-message: #You can have more lines.
  - "&aCongrats! You have officially been verified."

#Set the number of digits for the Punishment IDs.
punishment-id-length: 6 #The ID structure is '#'+the digits!

#Set the MINUTES for the inactivity. Helps to clean the AddingState map.
inactivity-minutes: 1

#Give rewards to the player when the player verifies.
rewards:
  toggle-giving-rewards: false #Whether you want to give rewards when a player verifies or not
  exp: 0 #In levels. It cannot be < 0!
  items: #Items, you have an example here of how to write them. You can add as many rewards as you want.
    bread:
      material: bread
      quantity: 32

#Configure the punishment messages.
player-punishments-messages:
  #The message when a player gets kicked from the MC server. Use '\n' for line breaks.
  #Placeholders: %scope% -> The scope for the kick
  #              %reason% -> The reason for the kick
  kick-message: "&cYou have been kicked from this server.\n\n&7Scope: %scope%\n&7Reason: &f%reason%"

  #The message when a player is permanently banned. Use '\n' for line breaks. THIS IS NOT TRIGGERED BY THE 'toggle' BOOLEAN!!!
  #Placeholders: %scope% -> The scope of the ban (Minecraft/Discord/Global)
  #              %reason% -> The reason for the ban
  #              %id% -> The ID of the ban. Useful for players to appeal!
  perm-ban-message: "&cYou are permanently banned from this server.\n\n&7Scope: %scope%\n&7Reason: &f%reason%\n\n&7Ban ID: &f%id%\n&7Use this ID to appeal."

  #The message when a player gets a perm-ban-warn.
  #Placeholders: %scope% -> The scope of the warning (Minecraft/Discord/Global)
  #              %reason% -> The reason of the warning
  perm-ban-warn-message:
    - "&4&l------------------------------------------"
    - " "
    - "&cYou got a permanent ban warning."
    - " "
    - "&7Scope: %scope%"
    - "&7Reason: &f%reason%"
    - " "
    - "&4&l------------------------------------------"

  #The message when a player is temporarily banned. Use '\n' for line breaks. THIS IS NOT TRIGGERED BY THE 'toggle' BOOLEAN!
  #Placeholders: %time_left% -> The duration of the ban
  #              %scope% -> The scope of the ban (Minecraft/Discord/Global)
  #              %reason% -> The reason for the ban
  #              %id% -> The ID of the ban. Useful for players to appeal.
  #              %expiration_time% -> The date when the ban will expire
  temp-ban-message: "&cYou are temporarily banned for &f%time_left% &cfrom this server.\n\n&7Scope: %scope%\n&7Reason: &f%reason%\n&7Expires at: &f%expiration_time%\n\n&7Ban ID: &f%id%\n&7Use this ID to appeal."

  #The message when a player gets a temporary ban warning. Use '&' for styles.
  #Placeholders: %scope% -> The scope of the warning (Minecraft/Discord/Global)
  #              %reason% -> The reason of the warning
  temp-ban-warn-message:
    - "&4&l------------------------------------------"
    - " "
    - "&cYou got a temporary ban warning."
    - " "
    - "&7Scope: %scope%"
    - "&7Reason: &f%reason%"
    - " "
    - "&4&l------------------------------------------"

  #The message when a player is permanently muted. Use '&' for styles.
  #Placeholders: %scope% -> The scope of the mute (Minecraft/Discord/Global)
  #              %reason% -> The reason of the mute
  #              %id% -> The id of the mute. Useful for players to appeal.
  perm-mute-message:
    - "&4&l------------------------------------------"
    - " "
    - "&cYou are permanently muted on this server."
    - " "
    - "&7Scope: %scope%"
    - "&7Reason: &f%reason%"
    - " "
    - "&7 Ban ID: &f%id%"
    - "&7 Use this ID to appeal!"
    - " "
    - "&4&l------------------------------------------"

  #The message when a player gets a permanent mute warning. Use '&' for styles.
  #Placeholders: %scope% -> The scope of the warning (Minecraft/Discord/Global)
  #              %reason% -> The reason of the warning
  perm-mute-warn-message:
    - "&4&l------------------------------------------"
    - " "
    - "&cYou got a permanent mute warning."
    - " "
    - "&7Scope: %scope%"
    - "&7Reason: &f%reason%"
    - " "
    - "&4&l------------------------------------------"

  #The message when a player is temporarily muted. Use '%' for styles.
  #Placeholders: %scope% -> The scope of the mute (Minecraft/Discord/Global)
  #              %reason% -> The reason of the mute
  #              %id% -> The id of the mute. Useful for players to appeal.
  #              %time% -> Displays the time of the mute
  #              %expiration_date% -> Displays the date when the mute expires
  temp-mute-message:
    - "&4&l------------------------------------------"
    - " "
    - "&cYou are temporarily muted for &f%time_left% &con this server."
    - " "
    - "&7Scope: %scope%"
    - "&7Reason: &f%reason%"
    - "&7Expires at: &f%expiration_time%"
    - " "
    - "&7Mute ID: &f%id%"
    - "&7Use this ID to appeal!"
    - " "
    - "&4&l------------------------------------------"

  #The message when a player gets a temp mute warning.
  #Placeholders: %scope% -> The scope of the mute warning (Minecraft/Discord/Global)
  #              %reason% -> The reason for the mute warning.
  temp-mute-warn-message:
    - "&4&l------------------------------------------"
    - " "
    - "&cYou got a temporary mute warning."
    - " "
    - "&7Scope: %scope%"
    - "&7Reason: &f%reason%"
    - " "
    - "&4&l------------------------------------------"

#Set the amount of warns that a player must have to trigger a punishment.
warns-amount: 3

#Configure all the chat-messages for DiscordUtils.
error-gui-message: "&cThere was error opening the GUI. Contact the server administrators about this."
command-no-permission-message: "&cYou don't have permission to run this command."
block-no-permission-message: "&cYou don't have permission to get the link."
fetching-data-task-in-progress-message: "&cYou must wait before attempting again!"
fetching-data-chat-message: "&8Fetching data..."
error-task-message: "&cThere was an error giving the discord link. Contact the server administrators about this."

#Configure all the SOUNDS for DiscordUtils. The default value for volume and sound is 1!
#TIP: do /playsound ... in Minecraft to HEAR the sound and see the sound's NAME.
exit-item-sound: "ui.button.click"
eis-volume: 1
eis-pitch: 1

give-verification-code-sound: "block.note_block.pling"
gvcs-volume: 1
gvcs-pitch: 1

player-has-verified-sound: "entity.player.levelup"
phvs-volume: 1
phvs-pitch: 1.4

boardcast-message-sound: "block.note_block.pling"
bms-volume: 1
bms-pitch: 1

get-discord-link-sound: "entity.player.levelup"
gdls-volume: 1
gdls-pitch: 1.4

gui-error-sound: "entity.enderman.teleport"
ges-volume: 1
ges-pitch: 1

fetching-data-task-in-progress-sound: "entity.villager.no"
fdtips-volume: 1
fdtips-pitch: 0.9

task-error-sound: "entity.enderman.teleport"
tes-volume: 1
tes-pitch: 1

player-no-permission-sound: "entity.enderman.teleport" #This sound comes up when the player clicks the discord-block and doesn't have 'discordutils.use' permission
pnps-volume: 1
pnps-pitch: 1

open-discord-gui-sound: "entity.experience_orb.pickup"
odgs-volume: 1
odgs-pitch: 1

#Configure the help book. Use '\n' to go on a new line in a page
help-message-book-pages:
  - " &9&l  DISCORD UTILS        HELP MANUAL\n\n&41. &l/dcutils configuration\n  &4->opens the Configuration GUI."
  - "&42. &l/dcutils reload\n  &4->reload the config file. Use when manually changing something in it.\n\n&43. &l/dcutils help\n  &4->brings up the help manual.\n\n&44. &l/discord\n  &4->Opens the GUI. Main command for players."